inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
    - Rakefile
    - config.ru

Rails:
  Enabled: true

Documentation:
  Enabled: false

Semicolon:
  Enabled: false

MethodLength:
  Severity: warning
  Max: 16

Style/AndOr:
  Enabled: false

Style/Lambda:
  Exclude:
      - config/**/*

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30
