dist: focal
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
services:
  - redis-server
addons:
  postgresql: 13
before_install:
  - gem install bundler -v 2.2.28
  - bundle config gems.contribsys.com $COVERALLS_REPO_TOKEN
  - yarn --ignore-engines
bundler_args: --without production doc
before_script:
  - bundle exec rails db:create db:schema:load RAILS_ENV=test

env:
  global:
    - MAINTENANCE_REDIS_HOST=localhost
    - MAINTENANCE_REDIS_PORT=6379
    - MAINTENANCE_REDIS_DB_INDEX=0
    - GIVE_SESSION_KEY=99999
    # These variables are intentionally blank in order establish the connection to the Postgresql server:
    - DB_ENV_POSTGRESQL_USER_TEST=
    - DB_ENV_POSTGRESQL_USER=
    - DB_ENV_POSTGRESQL_PASS_TEST=
    - DB_ENV_POSTGRESQL_PASS=
    - DB_PORT_5432_TCP_ADDR_TEST=
    - DB_PORT_5432_TCP_ADDR=
script:
  - bundle exec rails test
  - bundle exec standardrb
  - bundle exec bundle audit check --update --ignore CVE-2015-9284
  - bundle exec brakeman --ensure-latest -A -q --no-pager
  - yarn run improved-yarn-audit --ignore-dev-deps
