name: Ruby

on:
  pull_request:
    branches: [master]
  push:
    branches: [master,staging]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        env:
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}

      - name: Bundle audit
        run: bundle exec bundle audit check --update --ignore CVE-2015-9284

      - name: Brakeman
        run: bundle exec brakeman -A -q --ensure-latest --no-pager

      - name: StandardRB
        run: bundle exec standardrb --format simple

      - name: JavaScript Audit
        run: bin/importmap audit
